library(dplyr)
library(data.table)

rm(list = ls())


path <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/correlation_analysis"
setwd(path)


dt <- data.table::fread(file = "sample_details.tab", sep = "\t", header = T, stringsAsFactors = F, select = c("status", "Organism", "TF", "TimePoint", "IP_tag", "Rep", "NewSampleName", "DataPath"), data.table = T) %>% 
  dplyr::filter(status != "FAIL") %>% 
  dplyr::mutate(
    sample = paste(Organism, TF, TimePoint, IP_tag, sep = "_"),
    bwFile = paste(DataPath, "/", NewSampleName, "_normalized.bw", sep = "")
    ) %>% 
  data.table::as.data.table()



repDt <- data.table::dcast(data = dt,
                          formula = Organism + TF + TimePoint + IP_tag + sample ~ Rep,
                          value.var = c("NewSampleName", "bwFile")) %>% 
  dplyr::mutate(command = paste("bigWigCorrelate", bwFile_1, bwFile_2, sep = " ")) %>% 
  dplyr::rename(rep1 = "NewSampleName_1",
                rep2 = "NewSampleName_2")



#' Parse deeptools bigwig correlation matrix
#'
#' @param matFile correlation matrix file generated by deeptools' plotCorrelation tool
#' @param corrColName column name to be used for correlation column
#'
#' @return a dataframe with pairwise correlation information
#' @export
#'
#' @examples NA
parse_deeptools_corr_mat <- function(matFile, corrColName){
 
  ## read the deeptools correlation matrix file
  deeptoolsAll <- data.table::fread(file = matFile, sep = "\t", header = T, stringsAsFactors = F) %>%
    dplyr::rename(sampleId_1 = "V1") %>% 
    data.table::as.data.table()
  
  ## reshape the matrix to pairwise correlation table
  pairwiseCorr <- data.table::melt(data = deeptoolsAll, id.vars = c("sampleId_1"), variable.name = "sampleId_2", value.name = corrColName) %>%
    dplyr::mutate(
      sampleId_1 = gsub(pattern = "^'(.*)_normalized.bw'", replacement = "\\1", x = sampleId_1),
      sampleId_2 = gsub(pattern = "^'(.*)_normalized.bw'", replacement = "\\1", x = sampleId_2))
  
  return(pairwiseCorr)
}


## A. nidulans pearson correlation
anGene <- parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_gene.tab", corrColName = "genebody_correlation")
anPromoter <- parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_promoter.tab", corrColName = "promoter_correlation")
anBin <- parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_bin.tab", corrColName = "binwise_correlation")


## A. fumigatus pearson correlation
afuGene <- parse_deeptools_corr_mat(matFile = "Afu_bigwig_pearson_gene.tab", corrColName = "genebody_correlation")
afuPromoter <- parse_deeptools_corr_mat(matFile = "Afu_bigwig_pearson_promoter.tab", corrColName = "promoter_correlation")
afuBin <- parse_deeptools_corr_mat(matFile = "Afu_bigwig_pearson_bin.tab", corrColName = "binwise_correlation")


## A. flavus pearson correlation
aflGene <- parse_deeptools_corr_mat(matFile = "Afl_bigwig_pearson_gene.tab", corrColName = "genebody_correlation")
aflPromoter <- parse_deeptools_corr_mat(matFile = "Afl_bigwig_pearson_promoter.tab", corrColName = "promoter_correlation")
aflBin <- parse_deeptools_corr_mat(matFile = "Afl_bigwig_pearson_bin.tab", corrColName = "binwise_correlation")


## merge all sample pairwise correlations
geneCorr <- dplyr::bind_rows(anGene, afuGene, aflGene)
promoterCorr <- dplyr::bind_rows(anPromoter, afuPromoter, aflPromoter)
binCorr <- dplyr::bind_rows(anBin, afuBin, aflBin)



pairwiseCorrMat <- repDt %>% 
  dplyr::left_join(y = binCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2")) %>% 
  dplyr::left_join(y = geneCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2")) %>%
  dplyr::left_join(y = promoterCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2"))




data.table::fwrite(x = pairwiseCorrMat, file = "corr_commands.tab", sep = "\t", na = "NA", quote = F, col.names = T)



















