library(dplyr)
library(data.table)
library(tibble)
library(ComplexHeatmap)
library(circlize)
library(VennDiagram)
library(RColorBrewer)
library(chipmine)


rm(list = ls())

source(file = "E:/Chris_UM/Codes/GO_enrichment/topGO_functions.R")


path = "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN"

outDir = "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/TF_integration/laeA_20h_vs_48h"

if(!dir.exists(outDir)){
  dir.create(path = outDir)
}

setwd(path)

## 1) This script reads the (TF data + polII data cluster) files generated by TF_polII_integrationPlot.R script
## 2) Plot the SM genes and top10%(polII) genes heatmap for multiple TFs:
##    SM cluster + is_TF + polII_WT + is_top10%(polII_WT) + is_Peak(TF1) + polII_del_TF1 + is_top10%(polII_del_TF1) + is_Peak(TF2) + polII_del_TF2 + ...
##  For each polII sample, plot: polII FPKM + is_top10%(polII)
##  For each TF, plot: is_Peak(TF)
##


##################################################################################
comparisonName = "laeA_20h_vs_48h"
tf1 = "An_laeA_20h_HA"
tf2 = "An_laeA_48h_HA"
polII1 = "An_untagged_20h_polII"
polII2 = "An_untagged_48h_polII"

sampleList = c(tf1, tf2, polII1, polII2)


exptInfoFile ="E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/referenceData/sampleInfo.txt"
TF_dataPath = "TF_data"
polII_dataPath = "polII_data"

TF_analysisPath = "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/TF_integration"

anGenes = "E:/Chris_UM/Database/A_Nidulans/AN_genesForPolII.bed"
geneInfoFile = "E:/Chris_UM/Database/A_Nidulans/A_nidulans_FGSC_A4_geneClasses.txt"
clusterOrderFile = "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/referenceData/clusterOrder.txt"
mapFile = "E:/Chris_UM/Database/A_Nidulans/geneid2go.ANidulans.20171004.map"


outPrefix = paste(outDir, "/", comparisonName, sep = "")


##################################################################################
## read the experiment sample details and select only those which are to be plotted
exptData = get_sample_information(exptInfoFile = exptInfoFile,
                                  samples = sampleList,
                                  TF_path = TF_dataPath,
                                  polII_path = polII_dataPath)


polII_ids = exptData$sampleId[which(exptData$IP_tag == "polII")]
tfIds = exptData$sampleId[which(exptData$IP_tag != "polII")]

polIICols = sapply(c("is_expressed"),
                   FUN = function(x){ structure(paste(x, ".", polII_ids, sep = ""), names = polII_ids) },
                   simplify = F, USE.NAMES = T)

tfCols = sapply(c("hasPeak", "peakType", "tesPeakType", "peakDist", "summitDist", "upstreamExpr", "peakExpr", "relativeDist"),
                FUN = function(x){ structure(paste(x, ".", tfIds, sep = ""), names = tfIds) },
                simplify = F, USE.NAMES = T)

## genes to read
genesOfInterest = fread(file = anGenes, header = F, select = c(4), col.names = c("gene"), stringsAsFactors = F)


##################################################################################
## gene information annotations: cluster and TF
geneSet = add_gene_info(file = geneInfoFile, clusterDf = genesOfInterest)

head(geneSet)

expressionData = get_polII_expressions(exptInfo = exptData,
                                       genesDf = geneSet)

expressionData = get_TF_binding_data(exptInfo = exptData,
                                     genesDf = expressionData)


expressionData = get_peak_region_expression(exptInfo = exptData,
                                            genesDf = expressionData)

expressionData = get_upstream_expression(exptInfo = exptData,
                                         genesDf = expressionData)


log2FcPolIICol = paste("log2Fc.", polII1, "_vs_", polII2, sep = "")
upDownPolIICol = paste("upDownPolII.", polII1, "_vs_", polII2, sep = "")
log2FcTfUpCol = paste("log2FcTfUp.", tf1, "_vs_", tf2, sep = "")
upDownTfUpCol = paste("upDownTfUp.", tf1, "_vs_", tf2, sep = "")
relativeDistCol = paste("relativeDist.", tf1, "_vs_", tf2, sep = "")

expressionData = expressionData %>%
  mutate(!! log2FcPolIICol := log2( ( UQ(as.name(polII1)) / UQ(as.name(polII2)) ) + 0.01),
         !! log2FcTfUpCol := log2( ( UQ(as.name(tfCols$upstreamExpr[[tf1]])) / UQ(as.name(tfCols$upstreamExpr[[tf2]])) ) + 0.01 )
  ) %>%
  mutate(!! upDownTfUpCol := if_else(UQ(as.name(log2FcTfUpCol)) < 0, "Down", "Up" ),
         !! upDownPolIICol := case_when(
           UQ(as.name(log2FcPolIICol)) >= 0.7 ~ "Up",
           UQ(as.name(log2FcPolIICol)) <= -0.7 ~ "Down",
           TRUE ~ "similar"
         ),
         !! relativeDistCol := case_when(
           is.na(UQ(as.name(tfCols$peakDist[[tf1]]))) & is.na(UQ(as.name(tfCols$peakDist[[tf2]]))) ~ "none",
           UQ(as.name(tfCols$peakDist[[tf1]])) == UQ(as.name(tfCols$peakDist[[tf2]])) ~ "both",
           is.na(UQ(as.name(tfCols$peakDist[[tf1]]))) ~ tf2,
           is.na(UQ(as.name(tfCols$peakDist[[tf2]]))) ~ tf1,
           abs(UQ(as.name(tfCols$peakDist[[tf1]]))) < abs(UQ(as.name(tfCols$peakDist[[tf2]]))) ~ tf1,
           abs(UQ(as.name(tfCols$peakDist[[tf1]]))) > abs(UQ(as.name(tfCols$peakDist[[tf2]]))) ~ tf2,
           TRUE ~ "unknown"
         )
  )


# head(expressionData)

write.table(x = expressionData,
            file = paste(outDir, "/", comparisonName, "_mergedData.tab", sep = ""),
            sep = "\t",
            row.names = F, col.names = T, quote = F)

## select the genes which are expressed in polII sample
isExpressedDf = filter_at(.tbl = expressionData, .vars = polIICols$is_expressed, .vars_predicate = any_vars(. == "TRUE"))

##################################################################################
## plot SM genes

SM_genes_comparison_plot(data = expressionData,
                         orderFile = clusterOrderFile,
                         exptInfo = exptData,
                         outFile = paste(outPrefix, "_SMgenes.png", sep = ""),
                         name = comparisonName)


##################################################################################
## plot average profile plots

## get all the profile matrices
profileMatList = list()

for (i in 1:nrow(exptData)) {
  mat = import_profile_from_file(file = exptData$matFile[i],
                                 source = "deeptools",
                                 signalName = exptData$sampleId[i],
                                 selectGenes = isExpressedDf["gene"])
  
  profileMatList[[ exptData$sampleId[i] ]] = mat
  
}



lineColors = structure(.Data = c("red", "red", "blue", "blue"),
                       names = c(tf1, polII1, tf2, polII2))
lineShape = structure(.Data = c("solid", "twodash", "solid", "twodash"),
                      names = c(tf1, polII1, tf2, polII2))


## faceting mean profile plot
facetingDf = filter(.data = isExpressedDf,
                    UQ(as.name(upDownPolIICol)) != "similar",
                    UQ(as.name(relativeDistCol)) != "none"
)


groups = data.table(
  gene = facetingDf$gene,
  cluster = group_indices(facetingDf, !!as.name(upDownPolIICol), !!as.name(upDownTfUpCol))
) %>%
  mutate(cluster = paste("group_", cluster, sep = ""))


facetingDf = left_join(x = facetingDf, y = groups, by = "gene")

plist = list()

## get mean and sd profile for each cluster
groupMeanProfiles = facetingDf %>% group_by(cluster) %>%
  do(geneset_average_profile(exptInfo = exptData,
                             profileMats = profileMatList,
                             genes = .$gene,
                             cluster = unique(.$cluster)[1])
  )

grpStats = facetingDf %>% group_by(cluster) %>% summarise(geneCount = n())

p = ggplot(data = groupMeanProfiles) +
  geom_line(mapping = aes(x = bin, y = mean, group = sample, color = sample, linetype = sample),
            size = 1) +
  geom_segment(mapping = aes(x = 200, y = -8, xend = 400, yend = -8), size = 8, lineend = "butt", color = "grey70") +
  geom_hline(yintercept = -8, size = 2, color = "grey70") +
  annotate(geom = "text", x = 240, y = -8, label = "Scaled gene body", hjust = 0, vjust = 0.3) +
  scale_color_manual(values = lineColors) +
  scale_linetype_manual(values = lineShape) +
  scale_x_continuous(breaks = c(0, 100, 200, 400, 500),
                     labels = c("-2kb", "-1kb", "ATG", "STOP", "+1kb")) +
  ylab("Read coverage") +
  facet_grid(cluster ~ .) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold", size = 15),
        # legend.position = c(1, 1),
        # legend.justification = c(1.1, 1.1),
        legend.text = element_text(size = 13),
        legend.title = element_blank()
  )


png(filename = paste(outPrefix, "_meanProfiles.png", sep = ""), width = 2000, height = 2000, res = 180)
p
dev.off()

fwrite(grpStats, file = paste(outPrefix, "_groupStats.tab", sep = ""), sep = "\t", col.names = T, quote = F)

##################################################################################
## single plot
subDf = filter(.data = facetingDf,
               UQ(as.name(upDownPolIICol)) == "Up",
               UQ(as.name(upDownTfUpCol)) == "Up"
)

nrow(subDf)

meanProfile = geneset_average_profile(exptInfo = exptData,
                                      profileMats = profileMatList,
                                      genes = subDf$gene,
                                      cluster = unique(subDf$cluster)[1]
)


p1 = draw_avg_profile_plot(exptInfo = exptData,
                           profileMats = profileMatList,
                           lineColors = lineColors,
                           lineShape = lineShape,
                           genes = subDf["gene"]
)

p1



##################################################################################
## plot expressed or top 10% genes

row.names(isExpressedDf) = isExpressedDf$gene

plotOut = paste(outPrefix, "_compare_expressedGenes.png", collapse = "")
plotTitle = paste("All pol-II expressed genes for comparison", comparisonName,"\n")


expMultiTfData = geneset_multiTF_plot(data = isExpressedDf,
                                      exptInfo = exptData,
                                      outFile = plotOut,
                                      plotTitle = plotTitle,
                                      numClust = 6,
                                      name = comparisonName
)


# plot(expMultiTfData$dend)

write.table(x = expMultiTfData$df,
            file = paste(outPrefix, ".tab", sep = ""),
            sep = "\t",
            row.names = F, col.names = T, quote = F)



## do GO analysis for each cluster using topGo package
## GO enrichment table for all the clusters
goEnrichment_all = expMultiTfData$df %>%
  group_by(cluster) %>%
  do(get_topGO_enrichment(goMapFile = mapFile, genesOfInterest = .$gene))

fwrite(x = goEnrichment_all, file = paste(outPrefix, "_expressedGenes_GO.tab", sep = ""), sep = "\t", col.names = T, quote = F)



## function to generate the plot. to be called inside do()
topGO_and_plot_asDf = function(gn, tt, cl, pfx){
  tt = paste(tt, cl, sep = "\n")
  
  goData = get_topGO_enrichment(goMapFile = mapFile, genesOfInterest = gn)
  
  if(nrow(goData) == 0){
    return(data.frame(height = NA, width = NA, title = NA, res = NA, png = NA, stringsAsFactors = F))
  }
  
  topGoScatter = topGO_scatterPlot(df = goData, title = tt)
  
  ht = max(nrow(goData) * 80, 1500)
  wd = (min(max(nchar(as.character(goData$Term))), 80) * 30) * 1.5
  rs = max(min(wd, ht) / 12, 200)
  
  pngFile = paste(pfx, "_", cl, "_topGO.png", sep = "")
  
  png(filename = pngFile, width = wd, height = ht, res = rs)
  print(topGoScatter)
  dev.off()
  
  return(data.frame(height = ht,
                    width = wd,
                    res = rs,
                    count = nrow(goData),
                    title = tt,
                    png = pngFile,
                    stringsAsFactors = F))
}


## generate scatter plots for each
expTitle = paste("GO enrichment using topGO for polII expressed genes", sep = "")

topGOPlots_pkExp = expMultiTfData$df %>%
  group_by(cluster) %>%
  do(topGO_and_plot_asDf(gn = .$gene,
                         tt = expTitle,
                         cl = unique(.$cluster),
                         pfx = outPrefix
  )
  )



##################################################################################



goData = tf_binding_overlap(df = expressionData,
                            tf1 = "An_laeA_20h_HA",
                            tf2 = "An_laeA_48h_HA",
                            outPrefix = outPrefix,
                            topGoMapFile = mapFile)

















