library(chipmine)
require(XLConnect)
options(java.parameters = "- Xmx4g")
xlcFreeMemory()


rm(list = ls())


path <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN"
setwd(path)

## 1) This script takes the profile matrix *.gz file generated by deeptools
## 2) Generate a profile heatmap and cluster the genes by k-means or hierarchical clustering
## 3) It also reads a pol-II expression matrix and plot these expression values as heatmap

##################################################################################

TF_sample <- "An_kdmB_48h_HA_1"
input_sample <- "An_untagged_48h_HA_1"
polII_sample <- "An_untagged_48h_polII_1"
h3_sample <- "An_H3_48h_HIST_1"

name <- TF_sample

geneFilter <- c("AN5245", "AN3245")

# "deeptools", "miao", "normalizedmatrix", "normalizedmatrix_5kb"
matrixType <- "normalizedmatrix_5kb"
matrixDim = c(500, 200, 100, 10)

tfYlim = 0.996              ##0.999
poliiYlim = NULL           ##0.995



file_exptInfo <-"E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/data/referenceData/sampleInfo.txt"
TF_dataPath <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/data/TF_data"
polII_dataPath <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/data/polII_data"
hist_dataPath <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/data/histone_data"
file_genes <- "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN/data/referenceData/AN_genesForPolII.bed"


## additional annotations to add
# smGenes_file <- "AN_SM_genes.tab"
file_geneInfo <- "E:/Chris_UM/Database/A_Nidulans/A_nidulans_FGSC_A4_geneClasses.txt"


##################################################################################

outPath <- paste(TF_dataPath, "/", name, sep = "")
outPrefix_all <- paste0(outPath, "/", name, "_allGenes", collapse = "")
outPrefix_expressed <- paste0(outPath, "/", name, "_expressedGenes", collapse = "")
outPrefix_sm <- paste0(outPath, "/", name, "_SM_genes", collapse = "")
outPrefix_peaks <- paste0(outPath, "/", name, "_peaksGenes", collapse = "")
outPrefix_pkExp <- paste0(outPath, "/", name, "_pkExpGenes", collapse = "")


tf_info <- get_sample_information(exptInfoFile = file_exptInfo,
                                  samples = TF_sample,
                                  dataPath = TF_dataPath,
                                  matrixSource = matrixType)

input_info <- get_sample_information(exptInfoFile = file_exptInfo,
                                     samples = input_sample,
                                     dataPath = TF_dataPath,
                                     matrixSource = matrixType)


polII_info <- get_sample_information(exptInfoFile = file_exptInfo,
                                     samples = polII_sample,
                                     dataPath = polII_dataPath,
                                     matrixSource = matrixType)

hist_info <- get_sample_information(exptInfoFile = file_exptInfo,
                                   samples = h3_sample,
                                   dataPath = hist_dataPath,
                                   matrixSource = matrixType)


sampleInfo <- dplyr::bind_rows(tf_info, input_info, polII_info, hist_info)

geneSet <- data.table::fread(file = file_genes, header = F,
                             col.names = c("chr", "start", "end", "name", "score", "strand")) %>% 
  dplyr::mutate(length = end - start) %>% 
  dplyr::filter(! name %in% geneFilter)

excelOut <- paste0(outPrefix_all, "_clusters", ".xlsx", collapse = "")


hasPeakCol <- paste("hasPeak.", tf_info$sampleId, sep = "")
tssPeakTypeCol <- paste("peakType.", tf_info$sampleId, sep = "")
tssPeakPvalCol <- paste("pval.", tf_info$sampleId, sep = "")
tssPeakEnrichCol <- paste("enrichment.", tf_info$sampleId, sep = "")
tesPeakTypeCol <- paste("tesPeakType.", tf_info$sampleId, sep = "")
isExpCol <- paste("is_expressed.", polII_info$sampleId, sep = "")
peakDistCol <- paste("peakDist.", tf_info$sampleId, sep = "")

colPal = RColorBrewer::brewer.pal(9, "YlGnBu")
anWidth = unit(8, "mm")
peakAnArgs = get_peak_annotation_args(tssCol = tssPeakTypeCol, tesCol = tesPeakTypeCol)


anLables <- list()
anLables[[tssPeakTypeCol]] <- gsub("peakType", "TSS peak type\n", tssPeakTypeCol) %>% gsub("\\(|\\)", "", .)
anLables[[tesPeakTypeCol]] <- gsub("tesPeakType", "TES peak type\n", tesPeakTypeCol) %>% gsub("\\(|\\)", "", .)
anLables[[isExpCol]] <- gsub("is_expressed", "is expressed\n", isExpCol) %>% gsub("\\(|\\)", "", .)
anLables[["is_SM_gene"]] <- "SM gene"
anLables[["is_TF"]] <- "Transcription Factor"
anLables[["gene_length"]] <- "Gene Length"

profileColors <- list()
profileYlims <- list()

##################################################################################
## draw heatmap with all the genes

matList <- profile_matrix_list(exptInfo = sampleInfo,
                               geneList = geneSet$name,
                               source = matrixType,
                               up = matrixDim[1], target = matrixDim[2], down = matrixDim[3])

cat("## drawing heatmap with all the genes\n")

all_title <- paste0(name, ": all genes", collapse = "")



## check the distribution in data
quantile(matList[[TF_sample]], c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)
col_fun <- colorRamp2(quantile(matList[[TF_sample]], c(0.50, 0.995), na.rm = T), c("white", "red"))


profile1 <- profile_heatmap(profileMat = matList[[TF_sample]],
                            signalName = tf_info$sampleId,
                            columnTitle = tf_info$sampleId,
                            geneGroups = tf_info$clusterFile,
                            profileColor = col_fun,
                            ylimFraction = tfYlim)


## read polII expression data
expression1 <- get_polII_signal(file = polII_info$polIIExpFile,
                                title = polII_info$sampleId,
                                clusterData = profile1$cluster)

## add additional gene information columns like is_TF etc
clusterData <- add_gene_info(file = file_geneInfo, clusterDf = expression1$clusterDf)


## add macs2 peak calling information to clusterData
clusterData <- get_TF_binding_data(exptInfo = tf_info,
                                   genesDf = clusterData,
                                   allColumns = TRUE)

clusterData$geneLength <- clusterData$end - clusterData$start + 1

# 
# ## add peak region expression count
# clusterData <- get_peak_region_expression(exptInfo = tf_info,
#                                          genesDf = clusterData)
# 
# ## add 500bp upstream region expression count for each gene
# clusterData <- get_upstream_expression(exptInfo = tf_info,
#                                       genesDf = clusterData)
# 


quantile(expression1$log2_mat, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 1), na.rm = T)

polII_color <- colorRamp2(breaks = c(0, quantile(expression1$log2_mat, c(0.5, 0.8, 0.9, 0.92, 0.95, 0.97, 0.99, 0.995, 0.999))),
                          colors = c("white", RColorBrewer::brewer.pal(n = 9, name = "RdPu")))

## polII heatmap
polII_ht <- signal_heatmap(log2_matrix = expression1$log2_mat,
                           col_title = polII_info$sampleId,
                           legend_title = "log2(polII_FPKM + 1)",
                           color = polII_color)


## check the distribution in data
quantile(matList[[polII_sample]], c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)
polII_profCol <- colorRamp2(quantile(matList[[polII_sample]], c(0.01, 0.5, 0.995), na.rm = T), c("blue", "white", "red"))


profile2 <- profile_heatmap(profileMat = matList[[polII_sample]],
                            signalName = polII_info$profileName,
                            columnTitle = polII_info$sampleId,
                            geneGroups = clusterData,
                            profileColor = polII_profCol,
                            clusterColor = profile1$clusterColor)


## check the distribution in data
# quantile(matList[[input_sample]], c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)
# inputColFun <- colorRamp2(quantile(matList[[input_sample]], c(0.50, 0.995), na.rm = T), c("white", "red"))

profile3 <- profile_heatmap(profileMat = matList[[input_sample]],
                            signalName = input_info$sampleId,
                            columnTitle = input_info$sampleId,
                            geneGroups = clusterData,
                            profileColor = col_fun,
                            clusterColor = profile1$clusterColor,
                            ylimFraction = profile1$ylim)


## check the distribution in histone profile matrix
quantile(matList[[h3_sample]], c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)
h3_profCol <- colorRamp2(quantile(matList[[h3_sample]], c(0.2, 0.995), na.rm = T), c("black", "yellow"))

h3Profile <- profile_heatmap(profileMat = matList[[h3_sample]],
                             signalName = hist_info$sampleId,
                             columnTitle = hist_info$sampleId,
                             geneGroups = clusterData,
                             profileColor = h3_profCol,
                             clusterColor = profile1$clusterColor,
                             ylimFraction = tfYlim)


anGl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = geneSet$name)

htlist_allGenes <- profile1$rowAnno + anGl$an +
  profile3$heatmap + profile1$heatmap + polII_ht + profile2$heatmap + h3Profile$heatmap



# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_all, ".png", collapse = ""), width=8000, height=6000, res = 400)

draw(htlist_allGenes,
     main_heatmap = tf_info$sampleId,
     # annotation_legend_list = list(profile1$legend),
     column_title = all_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     gap = unit(c(2, 5, 10, 10, 10, 10), "mm"),
     padding = unit(rep(0.5, times = 4), "cm")
)

add_annotation_titles(annotations = c("gene_length"), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(profile1$clusterColor))


dev.off()

##################################################################################


profileColors[[tf_info$sampleId]] <- col_fun
profileColors[[input_info$sampleId]] <- col_fun
profileColors[[polII_info$sampleId]] <- polII_profCol
profileColors[[hist_info$sampleId]] <- h3_profCol

profileYlims[[tf_info$sampleId]] <- profile1$ylim
profileYlims[[input_info$sampleId]] <- profile1$ylim
profileYlims[[polII_info$sampleId]] <- profile2$ylim
profileYlims[[hist_info$sampleId]] <- h3Profile$ylim



##################################################################################
## Draw profile heatmap with the genes for which peak was called by macs2

cat("## drawing heatmap with the genes for which peak was called by macs2\n")

peaks_title <- paste0(name, ": genes for which macs2 peak detected", collapse = "")

peak_genes <- clusterData[which(clusterData[[hasPeakCol]]), ]
rownames(peak_genes) <- peak_genes$gene


peak_heatmaps <- multi_profile_plots(exptInfo = sampleInfo,
                                     genesToPlot = peak_genes$gene,
                                     clusters = peak_genes,
                                     clusterColor = profile1$clusterColor,
                                     profileColors = profileColors,
                                     matSource = matrixType,
                                     matBins = matrixDim,
                                     ylimFraction = profileYlims,
                                     plotExpression = TRUE,
                                     expressionData = peak_genes,
                                     expressionColor = polII_color)



## peak type annotation
peakTypeDf <- peak_genes[c(tssPeakTypeCol, tesPeakTypeCol)]

peaks_an <- HeatmapAnnotation(df = peakTypeDf,
                              which = "row",
                              col = peakAnArgs$col,
                              show_legend = F,
                              annotation_width = rep(anWidth, 2),
                              gap = unit(2, "mm")
)

## peak pval heatmap
quantile(peak_genes[[tssPeakPvalCol]], c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)

peakPvalCol <- colorRamp2(breaks = c(1, quantile(peak_genes[[tssPeakPvalCol]], c(0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.7, 0.9, 0.95), na.rm = T)),
                          colors = c("white", RColorBrewer::brewer.pal(n = 9, name = "YlOrRd")))



peak_pvalHt <- signal_heatmap(log2_matrix = as.matrix(peak_genes[tssPeakPvalCol]),
                              col_title = "macs2 log10(pval)",
                              legend_title = "macs2 log10(pval)",
                              color = peakPvalCol)


peaks_gl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = peak_genes$gene)


peaks_htlist <- peak_heatmaps$profileHeatmaps[[TF_sample]]$rowAnno +
  peaks_gl$an +
  peak_heatmaps$profileHeatmaps[[input_sample]]$heatmap +
  peak_heatmaps$profileHeatmaps[[TF_sample]]$heatmap +
  peak_pvalHt +
  peaks_an +
  peak_heatmaps$expressionHeatmaps[[polII_sample]] +
  peak_heatmaps$profileHeatmaps[[polII_sample]]$heatmap +
  peak_heatmaps$profileHeatmaps[[h3_sample]]$heatmap




# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_peaks, ".png", collapse = ""), width=8000, height=6000, res = 400)

draw(peaks_htlist,
     main_heatmap = tf_info$profileName,
     annotation_legend_list = list(peakAnArgs$lgd),
     column_title = peaks_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     # heatmap_legend_side = "bottom",
     # annotation_legend_side = "bottom",
     gap = unit(c(2, 5, 10, 10, 5, 2, 10, 10, 10), "mm"),
     padding = unit(rep(0.5, times = 4), "cm")
)


## decorate the annotations
add_annotation_titles(annotations = c("gene_length", colnames(peakTypeDf)), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(unique(peak_genes$cluster)))

dev.off()



peaks_htlist2 <- NULL
anGap <- numeric()
peaksSplit <- NULL

## make sure that the order of genes in the heatmap list and in the dataframe is same
if(all(rownames(peaks_htlist@ht_list[[tf_info$profileName]]@matrix) == peak_genes$gene)){
  ## set the row order by decreasing gene length
  # rowOrd <- order(peak_genes$geneLength, decreasing = TRUE)
  # sliceN <- 1
  
  ## set the row order by distance of the peak from ATG
  rowOrd <- order(peak_genes[[peakDistCol]], decreasing = TRUE)
  sliceN <- length(unique(peak_genes$cluster))
  peaks_htlist2 <- peak_heatmaps$profileHeatmaps[[TF_sample]]$rowAnno
  anGap <- c(2)
  peaksOrdOutFile <- paste0(outPrefix_peaks, "_ordPeakDist.png", collapse = "")
  
  ## set the row order by peak enrichment
  # rowOrd <- order(peak_genes[[tssPeakEnrichCol]], decreasing = TRUE)
  # sliceN <- 1
  # peaksOrdOutFile <- paste0(outPrefix_peaks, "_ordSignal.png", collapse = "")
  # peaksSplit <- rep(1, nrow(peak_genes))
}


# draw Heatmap with row order by gene length
peaks_htlist2 <- peaks_htlist2 +
  peaks_gl$an +
  peak_heatmaps$profileHeatmaps[[input_sample]]$heatmap +
  peak_heatmaps$profileHeatmaps[[TF_sample]]$heatmap +
  peak_pvalHt +
  peaks_an +
  peak_heatmaps$expressionHeatmaps[[polII_sample]] +
  peak_heatmaps$profileHeatmaps[[polII_sample]]$heatmap +
  peak_heatmaps$profileHeatmaps[[h3_sample]]$heatmap



# draw Heatmap and add the annotation name decoration
png(filename = peaksOrdOutFile, width=8000, height=6000, res = 400)

draw(peaks_htlist2,
     main_heatmap = tf_info$profileName,
     annotation_legend_list = list(peakAnArgs$lgd),
     column_title = peaks_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     gap = unit(c(anGap, 5, 10, 10, 5, 2, 10, 10, 10), "mm"),
     row_order = rowOrd,
     split = peaksSplit,
     padding = unit(rep(0.5, times = 4), "cm")
)


## decorate the annotations
add_annotation_titles(annotations = c("gene_length", colnames(peakTypeDf)), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = sliceN)

dev.off()



##################################################################################



##################################################################################
## Draw heatmap with only top 10% expressed genes

cat("## drawing heatmap with top 10% expressed genes\n")

expressed_title <- paste0(name, ": top 10% expressed polII genes", collapse = "")

## extract top 10% expressed genes from polII data
expressed_genes <- clusterData[which(clusterData[[isExpCol]]), ]


expressed_heatmaps <- multi_profile_plots(exptInfo = sampleInfo,
                                          genesToPlot = expressed_genes$gene,
                                          clusters = expressed_genes,
                                          clusterColor = profile1$clusterColor,
                                          profileColors = profileColors,
                                          matSource = matrixType,
                                          matBins = matrixDim,
                                          ylimFraction = profileYlims,
                                          plotExpression = TRUE,
                                          expressionData = expressed_genes,
                                          expressionColor = polII_color)



exp_gl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = expressed_genes$gene)


expressed_htlist <- expressed_heatmaps$profileHeatmaps[[TF_sample]]$rowAnno +
  exp_gl$an +
  expressed_heatmaps$profileHeatmaps[[input_sample]]$heatmap +
  expressed_heatmaps$profileHeatmaps[[TF_sample]]$heatmap +
  expressed_heatmaps$expressionHeatmaps[[polII_sample]] +
  expressed_heatmaps$profileHeatmaps[[polII_sample]]$heatmap +
  expressed_heatmaps$profileHeatmaps[[h3_sample]]$heatmap


## row order as decreasing polII signal
if(all(rownames(expressed_htlist@ht_list[[tf_info$profileName]]@matrix) == expressed_genes$gene)){

  expRowOrd <- order(expressed_genes[[polII_sample]], decreasing = TRUE)
}


## draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_expressed, ".png", collapse = ""), width=7500, height=6000, res = 400)

draw(expressed_htlist,
     main_heatmap = tf_info$profileName,
     column_title = expressed_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     gap = unit(c(2, 5, 10, 10, 10, 10, 10), "mm"),
     row_order = expRowOrd,
     padding = unit(rep(0.5, times = 4), "cm")
)

add_annotation_titles(annotations = c("gene_length"), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(unique(expressed_genes$cluster)))


dev.off()


##################################################################################



##################################################################################
## Draw profile heatmap with SM genes

cat("## drawing heatmap with SM genes\n")

sm_title <- paste0(name, ": Secondary metabolites genes", collapse = "")

sm_genes <- clusterData[which(clusterData$is_SM_gene), ]


sm_heatmaps <- multi_profile_plots(exptInfo = sampleInfo,
                                   genesToPlot = sm_genes$gene,
                                   clusters = sm_genes,
                                   clusterColor = profile1$clusterColor,
                                   profileColors = profileColors,
                                   matSource = matrixType,
                                   matBins = matrixDim,
                                   ylimFraction = profileYlims,
                                   plotExpression = TRUE,
                                   expressionData = sm_genes,
                                   expressionColor = polII_color)


sm_gl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = sm_genes$gene)


sm_htlist <- sm_heatmaps$profileHeatmaps[[TF_sample]]$rowAnno +
  sm_gl$an +
  sm_heatmaps$profileHeatmaps[[input_sample]]$heatmap +
  sm_heatmaps$profileHeatmaps[[TF_sample]]$heatmap +
  sm_heatmaps$expressionHeatmaps[[polII_sample]] +
  sm_heatmaps$profileHeatmaps[[polII_sample]]$heatmap +
  sm_heatmaps$profileHeatmaps[[h3_sample]]$heatmap


# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_sm, ".png", collapse = ""), width=8000, height=6000, res = 400)

draw(sm_htlist,
     main_heatmap = tf_info$profileName,
     # annotation_legend_list = list(sm_profile$legend),
     column_title = sm_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     gap = unit(c(2, 5, 10, 10, 10, 10), "mm"),
     padding = unit(rep(0.5, times = 4), "cm")
)

add_annotation_titles(annotations = c("gene_length"), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(unique(sm_genes$cluster)))

dev.off()

##################################################################################





##################################################################################
## plot polII expressed and TF bound genes together

cat("## drawing heatmap with top 10% polII expressed and TF bound genes together\n")

pkExp_title <- paste0(name, ": polII expressed and TF bound genes", collapse = "")


## select the genes which are expressed in polII sample OR have TSS peak
pkExp_genes <- filter_at(.tbl = clusterData, .vars = c(isExpCol, hasPeakCol), .vars_predicate = any_vars(. == "TRUE"))


pkExp_heatmaps <- multi_profile_plots(exptInfo = sampleInfo,
                                      genesToPlot = pkExp_genes$gene,
                                      clusters = pkExp_genes,
                                      clusterColor = profile1$clusterColor,
                                      profileColors = profileColors,
                                      matSource = matrixType,
                                      matBins = matrixDim,
                                      ylimFraction = profileYlims,
                                      plotExpression = TRUE,
                                      expressionData = pkExp_genes,
                                      expressionColor = polII_color)


pkExp_gl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = pkExp_genes$gene)

## annotations
peakAnArgs$col[["is_SM_gene"]] <- c("TRUE" = "orange", "FALSE" = "grey95")
peakAnArgs$col[["is_TF"]] <- c("TRUE" = "blue", "FALSE" = "grey95")
peakAnArgs$col[[isExpCol]] <- structure(c("green4", "grey95"), names = c("TRUE", "FALSE"))

pkExp_An <- HeatmapAnnotation(df = pkExp_genes[c("is_SM_gene", "is_TF", isExpCol, tssPeakTypeCol, tesPeakTypeCol)],
                              which = "row",
                              col = peakAnArgs$col,
                              show_legend = F,
                              annotation_width = rep(anWidth, 5),
                              gap = unit(2, "mm")
)


## legend for all the annotations
annLgd <- Legend(title = "\nGene categories",
                 at = c("SM gene", "Transcription Factor", "Expressed gene", "TF binding peak at TSS"),
                 type = "points",
                 pch = 15,
                 size = unit(5, "mm"),
                 grid_height = unit(5, "mm"),
                 grid_width = unit(5, "mm"),
                 legend_gp = gpar(col = c("orange", "blue", "green4", "sienna")),
                 title_gp = gpar(fontsize = 12, fontface = "bold"),
                 labels_gp = gpar(fontsize = 8)
)


## heatmap list
pkExp_htlist <- pkExp_heatmaps$profileHeatmaps[[TF_sample]]$rowAnno +
  pkExp_gl$an +
  pkExp_heatmaps$profileHeatmaps[[input_sample]]$heatmap +
  pkExp_heatmaps$profileHeatmaps[[TF_sample]]$heatmap +
  pkExp_heatmaps$expressionHeatmaps[[polII_sample]] +
  pkExp_heatmaps$profileHeatmaps[[polII_sample]]$heatmap +
  pkExp_An +
  pkExp_heatmaps$profileHeatmaps[[h3_sample]]$heatmap


## row order as decreasing polII signal
if(all(rownames(pkExp_htlist@ht_list[[tf_info$profileName]]@matrix) == pkExp_genes$gene)){
  pkExpOrd <- order(pkExp_genes[[peakDistCol]], pkExp_genes[[polII_sample]], decreasing = TRUE)
}



# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_pkExp, ".png", collapse = ""), width=8000, height=6000, res = 400)

draw(pkExp_htlist,
     main_heatmap = tf_info$profileName,
     annotation_legend_list = list(annLgd, peakAnArgs$lgd),
     column_title = pkExp_title,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     row_order = pkExpOrd,
     gap = unit(c(2, 5, 10, 10, 5, 10, 10), "mm"),
     padding = unit(rep(0.5, times = 4), "cm")
)


## decorate the annotations
add_annotation_titles(annotations = c("gene_length", "is_SM_gene", "is_TF", isExpCol, tssPeakTypeCol, tesPeakTypeCol),
                      anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(unique(pkExp_genes$cluster)))

dev.off()



##################################################################################



##################################################################################
## store the clusterData
write.table(clusterData, file = tf_info$mergedDataFile,
            col.names = T, row.names = F, sep = "\t", quote = F)

unlink(excelOut, recursive = FALSE, force = FALSE)
exc <- loadWorkbook(excelOut , create = TRUE)
xlcFreeMemory()
wrkSheet = name
createSheet(exc, name = wrkSheet)
createFreezePane(exc, sheet = wrkSheet, 2, 2)
setMissingValue(object = exc, value = "NA")
writeWorksheet(object = exc, data = clusterData, sheet = wrkSheet, header = T)
setAutoFilter(object = exc, sheet = wrkSheet, reference = aref(topLeft = "A1", dimension = dim(clusterData)))
xlcFreeMemory()
saveWorkbook(exc)

##################################################################################


cat(TF_sample, ": Done\n")







